jobs:
  - job:
      name : job3
      type: manifest
      steps:
        - GET resource1
        - GET resource2

  - job:
      name : job4
      type: manifest
      steps:
        - GET resource1
