jobs:
  - job:
      name : job1
      type: manifest
      steps:
        - GET resource2

  - job:
      name : job2
      type: manifest
      steps:
        - GET resource2
        - PUT resource2
        - ACT resource2
